Add config for enableScreenrecordChord (set to disabled). - This will fix a FC in DUtils/ActionHandler.
Logcat:
05-06 13:04:06.270  7076  7076 W ResourceType: No package identifier
when getting value for resource number 0x00000000
05-06 13:04:06.270  7076  7076 D AndroidRuntime: Shutting down VM
05-06 13:04:06.271  7076  7076 E AndroidRuntime: FATAL EXCEPTION: main
05-06 13:04:06.271  7076  7076 E AndroidRuntime: Process:
com.android.settings, PID: 7076
05-06 13:04:06.271  7076  7076 E AndroidRuntime:
java.lang.RuntimeException: Unable to start activity
ComponentInfo{com.android.settings/com.pixeldust.settings.preferences.ActionPickerDialogActivity}:
android.content.res.Resources$NotFoundException: Resource ID #0x0
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2795)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2871)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.app.ActivityThread.access$1300(ActivityThread.java:178)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1600)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.os.Handler.dispatchMessage(Handler.java:106)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.os.Looper.loop(Looper.java:164)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.app.ActivityThread.main(ActivityThread.java:6524)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
java.lang.reflect.Method.invoke(Native Method)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:460)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: Caused by:
android.content.res.Resources$NotFoundException: Resource ID #0x0
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:215)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.content.res.Resources.getBoolean(Resources.java:1057)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
com.android.internal.utils.du.DUActionUtils.getValue(DUActionUtils.java:389)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
com.android.internal.utils.du.DUActionUtils.getBoolean(DUActionUtils.java:427)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
com.android.internal.utils.du.ActionHandler.getSystemActions(ActionHandler.java:311)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
com.pixeldust.settings.preferences.CustomActionListAdapter.reloadActions(CustomActionListAdapter.java:61)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
com.pixeldust.settings.preferences.CustomActionListAdapter.<init>(CustomActionListAdapter.java:56)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
com.pixeldust.settings.preferences.ActionPickerDialogActivity.onCreate(ActionPickerDialogActivity.java:48)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.app.Activity.performCreate(Activity.java:6999)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.app.Activity.performCreate(Activity.java:6990)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
05-06 13:04:06.271  7076  7076 E AndroidRuntime: 	... 9 more

Signed-off-by: spezi77 <spezi7713@gmx.net>