Add Power+VolUp action to catch a partial area screenshot
- don't break Oreo accessibility volUp+VolDown actions
- fix aosp code bug causing FC on partial screenshot:
java.lang.IllegalArgumentException: x must be >= 0
- show a less troubled warning whe the screenshot is aborted
for any reason

huge thanks to Mazda-- who found the TAKE_SCREENSHOT_SELECTED_REGION
when Nougat landed.

Change-Id: I76028945995a91ef74790be76af7f809a124128a
Signed-off-by: spezi77 <spezi77@gmx.com>